"""Initial migration

Revision ID: 7873c5dca357
Revises:
Create Date: 2026-02-21 12:01:23.681426

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "7873c5dca357"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scanrecord",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("domain", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("malicious_status", sa.Integer(), nullable=False),
        sa.Column("inference_time_ms", sa.Float(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scanrecord_domain"), "scanrecord", ["domain"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_scanrecord_domain"), table_name="scanrecord")
    op.drop_table("scanrecord")
    # ### end Alembic commands ###
