"""add_user_whitelist_blacklist

Revision ID: edbc92bc7cc9
Revises: 7873c5dca357
Create Date: 2026-03-18 14:27:11.724597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'edbc92bc7cc9'
down_revision: Union[str, Sequence[str], None] = '7873c5dca357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userblacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userblacklist_domain'), 'userblacklist', ['domain'], unique=True)
    op.create_table('userwhitelist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userwhitelist_domain'), 'userwhitelist', ['domain'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userwhitelist_domain'), table_name='userwhitelist')
    op.drop_table('userwhitelist')
    op.drop_index(op.f('ix_userblacklist_domain'), table_name='userblacklist')
    op.drop_table('userblacklist')
    # ### end Alembic commands ###
