"""add_features_explanations_to_scanrecord

Revision ID: f82676780691
Revises: edbc92bc7cc9
Create Date: 2026-03-18 14:49:27.224262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f82676780691'
down_revision: Union[str, Sequence[str], None] = 'edbc92bc7cc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scanrecord', sa.Column('features_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('scanrecord', sa.Column('explanations_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scanrecord', 'explanations_json')
    op.drop_column('scanrecord', 'features_json')
    # ### end Alembic commands ###
